export { default as Home } from './Home/Home';
export { default as Art } from './Art/Art';
export { default as Computing } from './Computing/Computing';
export { default as FBMarketPlace } from './FBMarketPlace/FBMarketPlace';
export { default as Science } from './Science/Science';
export { default as About } from './About/About';
export { default as Contact } from './Contact/Contact';
export { default as PageNotFound } from './PageNotFound/PageNotFound';
export { default as UnderMaintenance } from './UnderMaintenance/UnderMaintenance';